export const MAX_PAGE_TEXT_CHARACTERS = 200_000;
export const MAX_PAGE_TEXT_NODES = 50_000;
export const MAX_SESSION_TEXT_CHARACTERS = 5_000_000;
export const MAX_SESSION_TEXT_DOCUMENTS = 500;
export const MAX_TEXT_LANGUAGE_LENGTH = 64;
